[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lexacube"
version = "0.1.0"
description = "LEXACUBE"
dependencies = [
    "pygame>=2.0.0",
    "paho-mqtt>=1.6.1"
]

[tool.setuptools.packages.find]
where = ["src"]
